version: '2'
services:
  app:
    ports:
      - "4200:4810"
    restart: always
    environment:
      HOST: 0.0.0.0:4000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config/prod.secret.exs:/srv/aria/config/prod.secret.exs
      - ./data/:/srv/aria/data/
